record:menu.o add.o print.o save.o load.o search.o exit.o delete.o reverse.o sort.o
	cc -o record menu.o print.o add.o save.o load.o search.o exit.o delete.o reverse.o sort.o
menu.o : menu.c
add.o  : add.c
print.o: print.c
save.o : save.c
load.o : load.c
search.o: search.c
exit.o: exit.c
delete.o: delete.c
reverse.o: reverse.c
sort.o: sort.c
